networks:
  default: mainnet-fork

autofetch_sources: True

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

compiler:
  evm_version: "london"
  solc:
    version: 0.8.7
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
    optimizer:
      enabled: true
      runs: 400
    outputSelection:
        "*": 
          "*": 
            - "storageLayout"

hypothesis:
  max_examples: 1